collections:
    maps:
        output: true
    backgrounds:
        output: false

defaults:
    - 
      scope:
        path: ""
        type: "maps"
      values:
        layout: "maps"
        permalink: "maps/:slug/index.html"
    - 
      scope:
        path: "gitzip/js"
      values:
        js: true
